{{- define "azure-devops-pipeline-agent.container" -}}
envFrom:
- configMapRef:
    name: {{ .Values.name }}
volumeMounts:
- mountPath: /azp
  name: azp-dir
- name: docker-graph-storage
  mountPath: /var/run/docker.sock
securityContext:
  privileged: {{ .Values.container.privileged }}
  {{- end -}}
