{{- define "azure-devops-pipeline-agent.container.tpl" -}}
name: {{ .Values.name | quote }}
image: {{ .Values.image | quote }}
imagePullPolicy: {{ .Values.container.imagePullPolicy | quote }}
securityContext:
  privileged: true
envFrom:
- configMapRef:
    name: {{ .Values.name }}
- name: docker-graph-storage
  mountPath: /var/run/docker.sock
{{- end -}}
