{{- define "azure-devops-pipeline-agent.container" -}}
envFrom:
- configMapRef:
    name: {{ .Values.name }}
volumeMounts:
- mountPath: /azp
  name: azp-dir
securityContext:
  privileged: true
{{- end -}}
