{{- include "helm-library.configmap" (list . "azure-devops-pipeline-agent.configmap") -}}
{{- define "azure-devops-pipeline-agent.configmap" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
{{- end -}}
