apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name | quote }}
  labels:
    {{- include "azure-devops-pipeline-agent.labels" . | nindent 4 }}
data:
  AZP_URL: {{ .Values.agent.url }}
  AZP_POOL: {{ .Values.agent.pool }}
