apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.name | quote }}
  labels:
    {{- include "azure-devops-pipeline-agent.labels" . | nindent 4 }}
spec:
  resyncInterval: {{ .Values.secret.resyncInterval | default 10 }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ .Values.secret.projectSlug | default "contabo-k-nii" | quote }}
        envSlug: {{ .Values.secret.envSlug | default "prod" | quote }}
        secretsPath: {{ .Values.secret.secretsPath | default "/" | quote }}
        recursive: {{ .Values.secret.recursive | default true }}
      credentialsRef:
        secretName: {{ .Values.secret.secretName | default "universal-auth-credentials" | quote }}
        secretNamespace: {{ .Values.secret.secretNamespace | default "infiscal" | quote }}
  managedSecretReference:
    secretName: {{ .Values.name }}
    secretNamespace: {{ .Values.namespace | default .Release.Namespace | quote }}
    creationPolicy: {{ .Values.secret.creationPolicy | default "Owner" | quote }}
