{{- include "helm-library.statefulset" (list . "azure-devops-pipeline-agent.statefulset") -}}
{{- define "azure-devops-pipeline-agent.statefulset" -}}
spec:
  template:
    spec:
      securityContext:
        fsGroup: {{ .Values.deployment.runAsUser }}
        runAsUser: {{ .Values.deployment.runAsUser }}
        runAsNonRoot: {{ .Values.deployment.runAsNonRoot }}
      containers:
      - {{ include "helm-library.container" (list . "azure-devops-pipeline-agent.container") }}
      volumes:
      - name: azp-dir
        emptyDir: {}
{{- end -}}
