apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name | quote }}
  labels:
    {{- include "azure-devops-pipeline-agent.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.deployment.replicas }}
  serviceName: {{ .Values.name | quote }}
  selector:
    matchLabels:
      {{- include "azure-devops-pipeline-agent.selector-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "azure-devops-pipeline-agent.labels" . | nindent 8 }}
      annotations:
        redeployOnChange: {{ randAlphaNum 5 | quote }}
    spec:
      volumes:
      - name: docker-graph-storage
        hostPath:
            path: /var/run/docker.sock
      containers:
      -
{{ include "azure-devops-pipeline-agent.container.tpl" . | indent 8 }}
