trigger:
  - main

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: John D Watson
    name: johnwatson484/azure-devops-templates
    ref: refs/tags/1

extends:
  template: build.yaml@templates
  parameters:
    name: azure-devops-pipeline-agent
    framework: helm
    deploy: false # Deployment needs to be manual using Helm CLI as the agent is the deployment target
    namespace: azure-devops
