image: johnwatson484/azure-devops-pipeline-agent
name: azure-devops-pipeline-agent

container:
  imagePullPolicy: Always

deployment:
  replicas: 3

agent:
  url: https://dev.azure.com/johnwatson484
  pool: Kubernetes

secret:
  secretsPath: /azure-devops-pipeline-agent

